### ISSUE TITLE
tlsdate default host using random timestamps

### ISSUE THREAD

**Issue by hannob** [ioerror/tlsdate#172]
It's becoming commonplace that TLS hosts use random timestamps.
Unfortunately this happened with www.ptb.de which is the default setting in tlsdate.

Some distributions already patch this, e.g. in gentoo it's set to www.google.com. This should be relatively reliable as google itself uses tlsdate in chromeos. At the very least it should be made sure that the default is someone who knows that they're used for that purpose (not sure if this happened with ptb.de)

**Comment by mhellwig** [comment]
I wonder if this is what happened to me earlier today? System time suddenly jumped to sometime in 2023 .. according to syslog, this was set by tlsdate.

**Comment by hartwork** [comment]
@mhellwig, if you are running tlsdate with www.ptb.de for a host... you know best :)

**Comment by nh2** [comment]
This gets worsened by the fact that once your date is bogus, TLS connections will fail, so you can't even use `tlsdate` to fix it.

**Comment by ioerror** [comment]
You have to manually run it against a host that gives the correct time. You may have to disable the date bounding but the signature can still be checked.

**Comment by vapier** [comment]
for posterity, this was addressed in commit 2049a7c43f591b490a9840454c272a8629cd1356 by switching www.ptb.de to google.com
