### ISSUE TITLE
www.ptb.de returning *highly* erratic timestamps

### ISSUE THREAD

**Issue by torrancew** [ioerror/tlsdate#173]
I know of at least one other user who was relying on a default config file, and also experienced this issue.

Effectively, at some point in the past 24 hours, the www.ptb.de source became *incredibly* unreliable and inconsistent:

    # tlsdate -n -H www.ptb.de -p 443 -V
    Tue Jun  7 18:45:59 PDT 2078
    # tlsdate -n -H www.ptb.de -p 443 -V
    Sat Nov 10 20:04:00 PST 2035
    # tlsdate -n -H www.ptb.de -p 443 -V
    Mon Sep 24 23:44:00 PDT 1990
    # tlsdate -n -H www.ptb.de -p 443 -V
    Wed Sep  2 22:56:15 PDT 2048

Perhaps this default should be changed? It would probably also make sense to reach out to the www.ptb.de folks, if there is any point of contact there, to let them know about this.

**Comment by irv** [comment]
Some explanation here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783174

**Comment by ioerror** [comment]
The default was changed in the last release.
