### ISSUE TITLE
Tlsdate has no installation candidate

### ISSUE THREAD

**Issue by ghost** [ioerror/tlsdate#188]
Using Kali (rolling on Raspberry Pi 3) I can't install tlsdate.
After updating and upgrading the system and issuing `apt-get install tlsdate` it returns the above error.
When trying `apt-cache search tlsdate` it outputs nothing.
I suspect the package has been marked obsolete in the repositories for Kali.
Now is there a way to still install it?
I tried various approaches already, including manually installing the .deb file with dpkg (returns an error with the libssl, libssl1.0.2 is installed!) and compiling it from this Git repo. `./autogen.sh` returns `32: ./autogen.sh: autoreconf: not found`.
I really need this package as I'm behind a restrictive firewall and the Raspberry Pi has no RTC.
Any help would be greatly appreciated.

**Comment by ghost** [comment]
Fixed. Apparently I missed a bunch of packages necessary for tlsdate to work, like libssl1.0.0.
Closing this issue but I still want to request support for the updated libssl library (1.0.2 and up).

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Tlsdate still has no installation candidate yet :(
